services:
  - type: web
    name: ai-news-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram-ai-news-bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID  
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false 